version: '2.1'

services:
  feedback:
    image: feedback
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js